collections:
  projects:
    output: true
  texts:
    output: true

# defaults declares which layout and values should be in the Front Matter by default

root: /Portfolio



baseurl: https://github.com/matak12m

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "texts"
    values:
      layout: "text"
  - scope:
      path: ""
    values:
      layout: "default"