collections:
  projects:
    output: true
  texts:
    output: true

# defaults declares which layout and values should be in the Front Matter by default

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"